"use client"
import 'react-toastify/dist/ReactToastify.css';
import "bootstrap/dist/css/bootstrap.min.css";
// import "bootstrap/dist/js/bootstrap.bundle.min";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { AuthProvider } from "../contexts/UserContext"
import Footer from '../components/Home/Footer';

//Pop up
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import '../styles/Aboutanimate.css'

//Amplify
import { Amplify } from 'aws-amplify';
import awsconfig from '../amplifyconfiguration.json';
import "@aws-amplify/ui-react/styles.css";
Amplify.configure(awsconfig, { ssr: true })
import { Authenticator } from '@aws-amplify/ui-react';
import Header from '../components/Home/Header';
import './index.scss';

//fontawesome icons
import '@fortawesome/fontawesome-free/css/all.css';

const inter = Inter({ subsets: ["latin"] });
import 'bootstrap/dist/css/bootstrap.css'
// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Authenticator.Provider>
                    <AuthProvider>
                        <div className="flex flex-col h-screen">
                            <ToastContainer
                                position="top-center"
                                autoClose={5000}
                                hideProgressBar
                                newestOnTop
                                closeOnClick
                                rtl={false}
                                pauseOnFocusLoss
                                draggable
                                pauseOnHover
                                theme="light"
                            />
                            <Header/>
                            {children}
                            <Footer />
                        </div>
                    </AuthProvider>
                </Authenticator.Provider>
            </body>
        </html>
    );
}
